apiVersion: v1
kind: Pod
metadata:
  name: crdp-pod
  labels:
    run: crdp
spec:
  containers:
    - image: thalesciphertrust/ciphertrust-restful-data-protection:latest
      imagePullPolicy: Always
      name: crdp-container
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8090
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /liveness
          port: 8090
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
      env:
        - name: KEY_MANAGER_HOST
          value: "192.168.59.119"
        - name: SERVER_MODE
          value: "no-tls"
        - name: REGISTRATION_TOKEN
          value: "QgrryKj059o3BOwz8ICIgLNGs4eVMQuV32MEJaPDiX2D0u8rjMDuFZw7llYa7EMe"
---
apiVersion: v1
kind: Service
metadata:
  name: srvc
  labels:
    run: crdp
spec:
  selector:
    run: crdp
  type: NodePort
  ports:
    - name: crdp-port
      port: 8090
      targetPort: 8090
      nodePort: 32083
