apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        firstname VARCHAR(255),
        lastname VARCHAR(255),
        ccnumber VARCHAR(255),
        cvv VARCHAR(255),
        expiry VARCHAR(255),
        ssn VARCHAR(255),
        mobile VARCHAR(255)
    );

